### ISSUE TITLE
Cetus never stops searching

### ISSUE THREAD

**Issue by Kirmo13** [Qwokka/Cetus#36] opened 2022-04-09 19:56 UTC
Title says it all,
I recently installed Cetus (from git clone..) and I tried following the tutorial step by step just to get some familiarity with it.  However, Cetus never returns anything when I search for a value. It just keeps searching indefinitely. How can I solve this?

Screenshot just shows what I see on my computer.
![Screenshot 2022-04-09 215401](https://user-images.githubusercontent.com/78370530/162589652-37b1194a-7d16-444c-bf2d-d2e4cb6e59f4.jpg)

**Comment by Qwokka** [comment] 2022-04-09 21:16
Hi @Kirmo13 

Can you try again on this game? http://webassembly.org.cn/demo/Tanks/

If it works okay on the tank game, the issue is probably with the specific game you're testing. I can look into it if you're okay sharing the game.

On the other hand, if searching is still broken on the tank game, I'd need to know the following:

* What browser are you using?
* Are there any errors in the browser console? (Accessible via CTRL+SHIFT+I in Chrome or Firefox)

Thanks,
Jack

**Comment by u9wy** [comment] 2022-04-13 00:34
> Hi @Kirmo13
> 
> Can you try again on this game? http://webassembly.org.cn/demo/Tanks/
> 
> If it works okay on the tank game, the issue is probably with the specific game you're testing. I can look into it if you're okay sharing the game.
> 
> On the other hand, if searching is still broken on the tank game, I'd need to know the following:
> 
> * What browser are you using?
> * Are there any errors in the browser console? (Accessible via CTRL+SHIFT+I in Chrome or Firefox)
> 
> Thanks, Jack

Hi @Qwokka ,

I also have the same problem. When i attempt to make a search it just doesn't work and i also cannot select different variable types. Reinstalling doesn't help.

I'm using this version: https://github.com/Qwokka/Cetus/issues/35#issuecomment-1086747510

**Comment by Qwokka** [comment] 2022-04-13 01:17
Hi @u9wy 

The only reason the "Value Type" selector should be disabled is if a search is currently in progress. When this happens, is there any output below the "Search" button? At minimum, it should have the "Restart Search" button which should unfreeze the search when clicked.

Also, do you have the same problem on the demo game I linked above?

Jack

**Comment by u9wy** [comment] 2022-04-13 01:21
> Hi @u9wy
> 
> The only reason the "Value Type" selector should be disabled is if a search is currently in progress. When this happens, is there any output below the "Search" button? At minimum, it should have the "Restart Search" button which should unfreeze the search when clicked.
> 
> Also, do you have the same problem on the demo game I linked above?
> 
> Jack

Hi @Qwokka .

Theres no output it only displays "searching" and yes the issue was present in the tank game as well. Funny enough i rolled back to version 1.2 and everything was working fine. Which is unusual because before i was having the same issue in the link i pasted in my previous comment.

**Comment by Qwokka** [comment] 2022-04-13 02:15
Thanks for the info. If you don't mind I'll ask a couple more questions to try to figure out what the issue is.

* What browser are you using?
* If using chrome, does the red "Error" button appear under the Cetus extension at the page `chrome://extensions/`?
    * If so, can you copy the contents of this error page here?
* If using firefox, you can go to the page `about:debugging#/runtime/this-firefox` and click "Inspect" next to Cetus. This should open up a browser console. Are there any lines highlighted in red? 
    * If so, can you copy them here?

Thanks for taking the time!
Jack

**Comment by u9wy** [comment] 2022-04-13 12:38
> Thanks for the info. If you don't mind I'll ask a couple more questions to try to figure out what the issue is.
> 
> * What browser are you using?
> * If using chrome, does the red "Error" button appear under the Cetus extension at the page `chrome://extensions/`?
>   
>   * If so, can you copy the contents of this error page here?
> * If using firefox, you can go to the page `about:debugging#/runtime/this-firefox` and click "Inspect" next to Cetus. This should open up a browser console. Are there any lines highlighted in red?
>   
>   * If so, can you copy them here?
> 
> Thanks for taking the time! Jack

Hi @Qwokka ,

I'm using Chrome 100.0.4896.64

Below is the error i get from the extension.
`{
    "name": "Cetus",
    "version": "1.03",
    "description": "Dynamic analysis extension for WASM",
    "manifest_version": 2,
    "content_scripts": [
        {
            "js": ["content/content.js"],
            "matches": ["<all_urls>"],
            "all_frames": true,
            "run_at": "document_start"
        }
    ],
    "permissions": ["activeTab", "storage"],
    "content_security_policy": "default-src 'self'; style-src 'unsafe-inline';",
    "web_accessible_resources": [
        "content/cetus.js",
        "content/init.js",
        "shared/wail.min.js/wail.min.js",
        "shared/utils.js",
        "content/thirdparty/stacktrace/stacktrace.min.js"
    ],
    "browser_action": {
        "default_title": "Cetus",
        "default_popup": "extension/popupview.html"
    },
    "devtools_page": "extension/devtools.html",
    "background": {
        "page": "extension/background.html",
        "persistent": true
    },
    "icons": {
        "16": "icons/cetus16.png",
        "48": "icons/cetus48.png",
        "128": "icons/cetus128.png"
    }
}
 `

**Comment by Qwokka** [comment] 2022-04-14 15:53
Just guessing based on that Chrome version but are you using ChromeOS? I've only tested Cetus on Chrome for Windows/Linux so it's possible there's issues with different OS's I haven't encountered.

If that is the case I'll try to get ChromeOS set up and fix whatever's going on.

**Comment by u9wy** [comment] 2022-04-14 15:54
> Just guessing based on that Chrome version but are you using ChromeOS? I've only tested Cetus on Chrome for Windows/Linux so it's possible there's issues with different OS's I haven't encountered.
> 
> If that is the case I'll try to get ChromeOS set up and fix whatever's going on.

@Qwokka  Yes i'm using chrome os, I was using Cetus without any issuse before however.

**Comment by almog-co** [comment] 2022-04-17 03:00
> Hi @Kirmo13
> 
> Can you try again on this game? http://webassembly.org.cn/demo/Tanks/
> 
> If it works okay on the tank game, the issue is probably with the specific game you're testing. I can look into it if you're okay sharing the game.
> 
> On the other hand, if searching is still broken on the tank game, I'd need to know the following:
> 
>     * What browser are you using?
> 
>     * Are there any errors in the browser console? (Accessible via CTRL+SHIFT+I in Chrome or Firefox)
> 
> 
> Thanks, Jack

Can confirm this happens on Firefox with this game https://primerlearning.org/. However, works fine on tank game.

**Comment by Qwokka** [comment] 2022-04-17 03:42
Hey @almog-co

What version of Cetus are you using? I fixed a bug with  primerlearning.org yesterday (#37). If you're still having trouble with it on the latest version, can you open a new issue?

On another note, we've pretty much hijacked this issue from the original submitter, so I'm going to close it and open an issue unique to incompatibilities with Chrome OS.

@Kirmo13 please feel free to re-open this if you have more to add. Thanks!

Jack

**Closed by Qwokka** 2022-04-17 03:42 UTC
