### ISSUE TITLE
Does this work on WebGL games from Unity?

### ISSUE THREAD

**Issue by TSSans-art** [Qwokka/Cetus#13] opened 2020-08-20 06:31 UTC
I have tried to use this on three separate WebGL Unity games, and I am unable to narrow down my search results. It always returns X results on the initial search, then the next search to narrow the results down always returns 0 results. I repeat the search using every size, same result. [Here is one of the games I tried](https://game317296.konggames.com/gamez/0031/7296/live/index.html)

Can anyone let me know if they can get Cetus working on this game? Don't know if it is Cetus or me that is the problem.

**Comment by cecio** [comment] 2020-08-20 07:55
DISCLAIMER: I'm not the author of the tool, so you may want to wait a more qualified reply. That said...

This is what I tried on Chrome 84.0.4147.125 and Firefox 80.0b8 (Dev Edition).
- started the game
- went in Cetus control panel (via Developer Tools)
- ran first search (Value: 123, Comparison: EQ, Type: i8)
- Cetus returned around 77,000 entries
- ...waited a while...
- clicked again on "Search" (without changing value)
- Cetus returned the same 77,000 entries minus a little amount

which is the expected result. Actually the second search, done on the subset, may have some of the value changed, so I expect something less than the initial one.
What I noticed is that Firefox is a looooot slower than Chrome returning the second result set (minutes, it looks hanging sometimes), but it works in any case.

The reason why you get 0 results on your second search, may have a lot of root cause, and it really depends and what you are looking for. Are you absolutely sure that your second search should give you some results? If  you rely on the numbers you see on the game screen, consider that these can be encoded in a lot of different way in memory, so it's not always a "one to one" relation.

Cheers,

**Comment by TSSans-art** [comment] 2020-08-20 08:56
> DISCLAIMER: I'm not the author of the tool, so you may want to wait a more qualified reply. That said...
> 
> This is what I tried on Chrome 84.0.4147.125 and Firefox 80.0b8 (Dev Edition).
> 
> * started the game
> * went in Cetus control panel (via Developer Tools)
> * ran first search (Value: 123, Comparison: EQ, Type: i8)
> * Cetus returned around 77,000 entries
> * ...waited a while...
> * clicked again on "Search" (without changing value)
> * Cetus returned the same 77,000 entries minus a little amount
> 
> which is the expected result. Actually the second search, done on the subset, may have some of the value changed, so I expect something less than the initial one.
> What I noticed is that Firefox is a looooot slower than Chrome returning the second result set (minutes, it looks hanging sometimes), but it works in any case.

Thanks for the reply. I too am on Chrome 84.0.4147.125 (Official Build) (64-bit). When I follow your steps, I get the same result as you describe. The steps I am doing to try and find values is as follows:

- Get a few coins (12 for example)
- Set speed hack to 0 and enable it (pause)
- Search for (Value: 12, Comparison: EQ, Type: i8)
- Get 108520 or so results
- Disable speed hack (un-pause)
- Wait until you have more coins (20 for example)
- Re-enable speed hack at 0 (pause)
- Search for new value 20
- 0 results
- Repeat whole process again but using i16, Still no results on 2nd search
- Repeat whole process again but using i32, Still no results on 2nd search
...
- Repeat whole process again but using f64, Still no results on 2nd search
I am pretty sure I am not using it incorrectly. 

> The reason why you get 0 results on your second search, may have a lot of root cause, and it really depends and what you are looking for. Are you absolutely sure that your second search should give you some results? If you rely on the numbers you see on the game screen, consider that these can be encoded in a lot of different way in memory, so it's not always a "one to one" relation.

Hmm, this is an interesting point you've brought up. I suspect this maybe be what is happening here. I might have to try using unknown starting value with  LT and GT instead of exact numbers. Is there any way to know what type the value I am looking for is (in this case, the coin value)? As it is right now, I just have to try all of them.

**Comment by cecio** [comment] 2020-08-20 11:47
The only thing that came in my mind is to use differential search and then patience...to figure out what is doing what ;-)

Sorry, at the moment I don't have anything else that came in my mind, may me someone else has smarter suggestions.... :-)

**Comment by TSSans-art** [comment] 2020-08-30 07:59
I think it would be handy if you could export your bookmarks to a file, and add names for bookmarks. So you could label address **`0x0122f908`** as **`Gold`** and then save all that to a file that you can import back next time you load up that game. And maybe a way to add addresses to the bookmark tab, like a **`+ Add Bookmark`** button where you can just type in the address and type (and label) without having to search for the address every time you load the game.

**Comment by TristonStuart** [comment] 2020-08-31 17:33
I just wanted to answer this by saying yes it works well for unity wasm games.
As far as finding a gold value I actually recommend using cheat engine to find the value and then using cetus to find the wasm code. Cheat engine can give you a lot better sense of the memory you are dealing with. I would also recommend looking up tutorials on finding values with cheat engine that can change/be encrypted.

**Comment by TristonStuart** [comment] 2020-08-31 19:56
Also, the values are stored as doubles. And for example, if you see 11.1B, the number stored isn't 11.1, its 11,100,000. So you probably want to find the values early game.

**Comment by Qwokka** [comment] 2020-09-01 00:27
@TSSans-art This is a great idea. I'm going to add this as a separate issue so that I can track it. The main issue is making the changes in the UI. A friend and I are working on a pretty big UI overhaul as is so this may wait until that's complete.

In the meantime you can manually add bookmarks from the console like so:

```javascript
cetus.addBookmark(address, type);
```

So if you want to save a bookmark at address 0x41424344 of type "f32" you'd do:

```javascript
cetus.addBookmark(0x41424344, "f32");
```

This of course doesn't handle exporting bookmarks, but it's better than starting from scratch each time.

Thanks for the great suggestion!

**Comment by TSSans-art** [comment] 2020-09-01 00:28
@TristonStuart Thanks for the advice. I have been able to find the values I am looking for. Could you elaborate on this
>using cetus to find the wasm code

Once I have the address then how can I find the wasm function?

**Comment by TristonStuart** [comment] 2020-09-01 03:37
> @TristonStuart Thanks for the advice. I have been able to find the values I am looking for. Could you elaborate on this
> 
> > using cetus to find the wasm code
> 
> Once I have the address then how can I find the wasm function?

Well you want to find the value in cheat engine, then pause the game and set the value to a low number, like 200. Then search it in cetus, then change it again with cheat engine. Do this till you find the right value. Then you can read/write watch it to find the wasm code that changes it

**Comment by TSSans-art** [comment] 2020-09-01 04:03
@TristonStuart 
>Then you can read/write watch it to find the wasm code that changes it

Yeah I thought you'd say that. I have tried read watch/watch write in that tank game and it seemed to work fine there. In [this game](https://game317296.konggames.com/gamez/0031/7296/live/index.html) though (the game I linked in my original issue), finding the gold value (always seems to be 0x0122f908), using freeze, read watch and write watch doesn't give me any stack trace of functions or anything, it seemingly does nothing. I have said as much a couple of times in this thread. Don't know if @Qwokka saw that part and is looking into it or not. But for this game at least, It doesn't work for me. @TristonStuart if you could find the gold value in the game I linked (I think it should be the same address as I listed) and if you could try using read/write watch on that address and just let me know if it does anything for you, please let me know

**Comment by Qwokka** [comment] 2020-09-01 04:08
@TSSans-art I just tested setting a watchpoint on the gold value and I'm getting the same behavior. I'll push a fix tonight or tomorrow. Sorry about that!

**Comment by TSSans-art** [comment] 2020-09-01 17:53
@Qwokka I'm so glad to hear that, thanks!

**Comment by Qwokka** [comment] 2020-09-02 03:00
I believe I've got this fixed with 55089102c097c6fe3f7d0aef8709a1dba0344478. I was able to find the gold value and set read/write/freeze on it without errors.

This was a bit of a big improvement that I've been procrastinating on for a while. So there may be some bugs to shake out, but it seems reliable in my testing.

**Comment by TSSans-art** [comment] 2020-09-02 23:49
@Qwokka Ah yes it does seems to work now. Thanks so much for that, this is a great tool

**Comment by Qwokka** [comment] 2020-09-08 03:22
I'm gonna close this but feel free to reopen or create a new issue if you have other problems. This game was a great example of a few different edge cases so it was fun to look at.

**Closed by Qwokka** 2020-09-08 03:22 UTC
